/*
 * Copyright (C) 2026 aisleron.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

val coverageExcludes = listOf(
    "**/R.class",
    "**/R$*.class",
    "**/BuildConfig.*",
    "**/Manifest$*.*",
    "**/theme/Theme*",
    "**/theme/Type*",
    "**/*Preview*.*",
    "**/*PreviewKt*.*",
    "**/*ComposableSingletons*.*"
)

fun JacocoReport.configureReport() {
    group = "verification"

    reports {
        html.required = true
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/codeCoverage/html"))
    }

    // Class files generated by the Kotlin compiler.
    classDirectories.setFrom(
        fileTree(layout.buildDirectory.dir("intermediates/built_in_kotlinc/debug/compileDebugKotlin/classes")) {
            exclude(coverageExcludes)
        }
    )

    // Source sets that coverage should be reported for.
    sourceDirectories.setFrom(files("$projectDir/src/main/kotlin"))

    // Collection of execution data files to analyze.
    executionData.setFrom(
        fileTree(layout.buildDirectory) {
            include("outputs/**/*.exec", "outputs/**/*.ec")
        }
    )

    onlyIf {
        executionData.files.any { it.exists() }
    }
}

tasks.register<JacocoReport>("codeCoverage") {
    // Run with ./gradlew codeCoverage
    description = "Generates coverage report from existing execution data."
    configureReport()
}

tasks.register<JacocoReport>("testsWithCodeCoverage") {
    // Run with ./gradlew testsWithCodeCoverage
    description = "Runs all tests and then generates the coverage report."

    dependsOn(tasks.named("testDebugUnitTest"))
    dependsOn(tasks.named("connectedDebugAndroidTest"))

    configureReport()
}